#
name: training
channels:
  - defaults
dependencies:
  - python>=3.6
  - pip
  - pip:
    - numpy==1.17.0
    - pandas==0.25.0
    - xlrd==1.2.0
    - scipy==1.3.0
    - plotly==4.0.0
    - dash==1.0.2
    - matplotlib==3.1.1