# I have a lot of trouble with conda creating virtual environments within
# the BAH network due to SSL issues.  I have trouble outside the BAH network
# due to issues with conda calling the pip subprocess.  I would recommend 
# using the `python -m venv training` and `pip install -r requirements.txt`.
# This file is not complete because I have a lot of trouble testing it.  
# If you do choose to `conda create -f environment.yml`, follow it up with
# `pip install -r requirements.txt`
name: training
channels:
  - defaults
dependencies:
  - python>=3.6
  - pip
  - pip:
    - numpy==1.17.0
    - pandas==0.25.0
    - xlrd==1.2.0
    - scipy==1.3.0
    - plotly==4.0.0
    - dash==1.0.2
    - matplotlib==3.1.1
    - sphinx==2.1.2
